//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductXDetails
    {
        public int ProductDetailID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> UnitCostPrice { get; set; }
        public string Location { get; set; }
        public Nullable<int> ThresholdQuantity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
